apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jretirewise
  labels:
    app: jretirewise
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: jaycurtis.org
    http:
      paths:
      - path: /jretirewise/
        pathType: Prefix
        backend:
          service:
            name: prod-jretirewise-jretirewise-web-service
            port:
              name: http
